### ISSUE TITLE
安装后，未找到应用

### ISSUE THREAD

**Issue by Adiao1973** [GSWXXN/UnlockMiLink#1]
小米平板5pro安装LSPosed后找不到app图标，在设置中能搜索到，使用adb打开也无法打开

**Comment by GSWXXN** [comment]
模块就是没有桌面图标的，可以在这里进入模块设置

<img src="https://user-images.githubusercontent.com/34705923/184665490-fbfa26b4-4ffa-4e7a-8cea-999c82308362.jpg" width=30%>
