### ISSUE TITLE
PC无法搜索到设备

### ISSUE THREAD

**Issue by P0etry-rain** [GSWXXN/UnlockMiLink#3]
反馈一下 无法搜索到设备
问题：无法搜索到设备
手机设备：红米k40s，有lsposed框架，安装了小米不妙享1.5。投屏13.1版本，互联通信服务2.11，MIUI+ 3.6。
电脑设备：华硕天选一，小米妙享3.0.1.56。
补充：蓝牙，WiFi均开启。处于同一局域网。
已经想不到还有其他什么地方可能出问题导致连不上了😫
![KP$U5{XJ(03WVJ~9VJ4{(G](https://user-images.githubusercontent.com/52886465/188464885-43279a74-4a0b-4a62-9242-0528b5cc6ff9.jpg)
![Snipaste_2022-09-05_20-59-09](https://user-images.githubusercontent.com/52886465/188465395-1a0757c1-2a75-41a3-9cac-83a1d5907cec.jpg)

**Comment by GSWXXN** [comment]
MIUI+ Beta版和互联通信服务本太低了

[需要升级的妙享组件下载链接](https://wwp.lanzoub.com/b027lfxdc)
密码:6ca1

**Comment by P0etry-rain** [comment]
> MIUI+ Beta版和互联通信服务本太低了
> 
> [需要升级的妙享组件下载链接](https://wwp.lanzoub.com/b027lfxdc) 密码:6ca1

已更新，问题依旧😥

**Comment by GSWXXN** [comment]
> > MIUI+ Beta版和互联通信服务本太低了
> > [需要升级的妙享组件下载链接](https://wwp.lanzoub.com/b027lfxdc) 密码:6ca1
> 
> 已更新，问题依旧😥

扫描手动连接，可以连接上吗

**Comment by P0etry-rain** [comment]
> > > MIUI+ Beta版和互联通信服务本太低了
> > > [需要升级的妙享组件下载链接](https://wwp.lanzoub.com/b027lfxdc) 密码:6ca1
> > 
> > 
> > 已更新，问题依旧😥
> 
> 扫描手动连接，可以连接上吗

已尝试，可以连接。出现一次手机死机和一次扫码闪退。

**Comment by P0etry-rain** [comment]
顺便一说，仅能通过扫码连接，手机和电脑都搜索不到对方设备。
